# Generated by Django 3.2.19 on 2023-07-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f_flowsen_setting',
            old_name='ff',
            new_name='ff1',
        ),
        migrations.RenameField(
            model_name='p_flowsen_setting',
            old_name='ff',
            new_name='ff2',
        ),
    ]
