# Generated by Django 3.2.19 on 2023-07-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_auto_20230715_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm_repo_daily',
            name='custid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atm_repo_daily',
            name='whr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atm_repo_hourly',
            name='custid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atm_repo_hourly',
            name='whr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atm_repo_monthly',
            name='custid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atm_repo_monthly',
            name='whr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atm_repo_yearly',
            name='custid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atm_repo_yearly',
            name='whr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disp_atm',
            name='custid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disp_atm',
            name='whr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
