# Generated by Django 3.2.19 on 2023-07-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_auto_20230718_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm_repo_daily',
            name='custid',
        ),
        migrations.RemoveField(
            model_name='atm_repo_hourly',
            name='custid',
        ),
        migrations.RemoveField(
            model_name='atm_repo_monthly',
            name='custid',
        ),
        migrations.RemoveField(
            model_name='atm_repo_yearly',
            name='custid',
        ),
    ]
