# Generated by Django 3.2.19 on 2023-07-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_auto_20230718_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-07-18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device_info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
