# Generated by Django 3.2.19 on 2023-07-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0005_auto_20230719_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm_repo_daily',
            name='whr',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atm_repo_hourly',
            name='whr',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atm_repo_monthly',
            name='whr',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atm_repo_yearly',
            name='whr',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
